# Generated by Django 2.2.6 on 2019-11-05 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_posts_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='photo_main',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y%m%d/'),
            preserve_default=False,
        ),
    ]
